Add sorting and filtering options, enhance accessibility
humanoidsbv/team-awesome-bram pull request #32
Opened 2022-03-03 15:06 UTC by brambrink

2022-03-07 15:11 UTC, RubenWerdmuller requested changes

2022-03-07 15:11 UTC, RubenWerdmuller commented on src/components/logo/Logo.styled.ts
>    cursor: pointer;
You changed this into a div, but the mouse still wants to point at it

2022-03-07 15:11 UTC, RubenWerdmuller commented on src/components/menu-button/MenuButton.tsx
> +    <HamburgerIcon arial-label="menu" />
`arial` isn't valid, is it?

2022-03-07 15:11 UTC, RubenWerdmuller commented on src/components/time-entries/TimeEntries.tsx
> +  const [clientFilter, setClientFilter] = useState("");
Remove empty line

2022-03-07 15:12 UTC, RubenWerdmuller commented
Nice busy! 👍

2022-03-07 15:15 UTC, brambrink commented on src/components/logo/Logo.styled.ts
>    cursor: pointer;
`  cursor: pointer;` makes sure the pointer is still pointing add it!

2022-03-07 15:16 UTC, brambrink commented on src/components/menu-button/MenuButton.tsx
> +    <HamburgerIcon arial-label="menu" />
I get confused with the font, should be aria indeed

2022-03-07 15:25 UTC, RubenWerdmuller approved these changes

2022-03-08 09:43 UTC, fabianovangool approved these changes
Right on!

2022-03-08 09:59 UTC, merged