Implement GraphQL
humanoidsbv/team-awesome-bram pull request #41
Opened 2022-03-16 15:08 UTC by brambrink

2022-03-16 15:21 UTC, RubenWerdmuller commented
[Very nice!](https://www.youtube.com/watch?v=LBduNcf1eQc&ab_channel=georgenajjar)

2022-03-16 15:26 UTC, RubenWerdmuller requested changes

2022-03-16 15:26 UTC, RubenWerdmuller commented on package.json
> +    "dev": "next & npm run json-server & npm run json-graphql-server",
Rather than starting both the `REST` and `GraphQL` server, create separate commands for these

2022-03-16 15:26 UTC, RubenWerdmuller commented on pages/_app.tsx
> +import client from "../apollo-client";
Use named export for `client`

2022-03-16 15:26 UTC, RubenWerdmuller commented on pages/index.tsx
> +import { GET_DATA } from "../graphql/time-entries";
Use more descriptive name for data

2022-03-16 15:26 UTC, RubenWerdmuller commented on pages/index.tsx
> +      <title> Time entries | Team Awesome Bram </title>
Remove spacing

2022-03-16 15:26 UTC, RubenWerdmuller commented on pages/team-members.tsx
> +      <title> Team members | Team Awesome Bram </title>
Trim title

2022-03-16 15:26 UTC, RubenWerdmuller commented on src/components/team-members/TeamMembers.tsx
> +    });
```suggestion
    const {emailAddress, firstName, lastName, role, employer, startingDate} = newTeamMember
    addNewTeamMember({
      variables: {emailAddress, firstName, lastName, role, employer, startingDate},
    });
```

2022-03-17 08:45 UTC, brambrink commented on pages/index.tsx
> +import { GET_DATA } from "../graphql/time-entries";
This contains both the client- and time entries, I am struggling to find a better name for this, any suggestions?

2022-03-17 08:49 UTC, brambrink commented on src/components/team-members/TeamMembers.tsx
> +    });
This does not work this way with GraphQL I think. Right now, I am setting the state using: 
```
 const [addNewTeamMember] = useMutation(ADD_TEAM_MEMBER, {
    onCompleted: (data) => {
      setTeamMembers([...teamMembers, data.createTeamMember]);
    },
  });```

2022-03-17 09:05 UTC, RubenWerdmuller requested changes

2022-03-17 09:05 UTC, RubenWerdmuller commented on pages/team-members.tsx
> +import { GET_TEAM_MEMBERS } from "../src/graphql/team-members";
👌!

2022-03-17 09:07 UTC, brambrink commented on pages/index.tsx
> +import { GET_DATA } from "../graphql/time-entries";
Nice, thanks!

2022-03-17 09:12 UTC, RubenWerdmuller approved these changes
Nice 🔥🔥🔥🔥💧💧🧯🧑‍🚒🧑‍🚒 🚒

2022-03-17 09:51 UTC, nathaliebru approved these changes
Looks gooooood!

2022-03-17 09:51 UTC, nathaliebru commented on package.json
>      "json-server": "json-server --watch db.json --port 3004",
localhost:3333 isn't running when running `npm run dev`, change your `json-server` script to `json-server --watch db.json --port 3004 & json-graphql-server db.json --p 3333`

2022-03-17 09:51 UTC, merged